name: Build & Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - '**'
      - '!README.md'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercased owner as env
        id: prep
        run: echo "REPO_OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/$REPO_OWNER_LC/qr-generator:latest .

      - name: Push image
        run: docker push ghcr.io/$REPO_OWNER_LC/qr-generator:latest